apiVersion : apps/v1
kind: Deployment
metadata:
  name: tapaswibuildjarfileinsidedockercontainer 
spec:
  replicas: 1
  restartPolicy: Always
  selector:
    matchLabels:
      app: tapaswibuildjarfileinsidedockercontainer
  template:
    metadata:
      labels:
        app: tapaswibuildjarfileinsidedockercontainer 
    spec:
      containers:
        - name: tapaswibuildjarfileinsidedockercontainer 
          image: myappreg.azurecr.io/tapaswibuildjarfileinsidedockercontainer
          ports:
          - containerPort: 80
