apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myapp-bac7"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myapp-bac7"
  template:
    metadata:
      labels:
        app: "myapp-bac7"
    spec:
      containers:
        - name: "myapp-bac7"
          image: "sampledeployment.azurecr.io/myapp"
          ports:
          - containerPort: 80